// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6hhRq3C_V8VCfCu2V8DosRT29aar5F8',
    appId: '1:1039245326162:web:0525d7fced5b4d6d9aac8b',
    messagingSenderId: '1039245326162',
    projectId: 'flutter-auth-7e3ae',
    authDomain: 'flutter-auth-7e3ae.firebaseapp.com',
    storageBucket: 'flutter-auth-7e3ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5oTqya900jAjrgajdmEto3IlzooSfUEk',
    appId: '1:1039245326162:android:2343e51dc5d0ec249aac8b',
    messagingSenderId: '1039245326162',
    projectId: 'flutter-auth-7e3ae',
    storageBucket: 'flutter-auth-7e3ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE7ne5TEbcbfNVVm3y7GK93sOq4R1jRso',
    appId: '1:1039245326162:ios:ddc3b261015a3fe49aac8b',
    messagingSenderId: '1039245326162',
    projectId: 'flutter-auth-7e3ae',
    storageBucket: 'flutter-auth-7e3ae.firebasestorage.app',
    iosBundleId: 'com.example.authTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE7ne5TEbcbfNVVm3y7GK93sOq4R1jRso',
    appId: '1:1039245326162:ios:ddc3b261015a3fe49aac8b',
    messagingSenderId: '1039245326162',
    projectId: 'flutter-auth-7e3ae',
    storageBucket: 'flutter-auth-7e3ae.firebasestorage.app',
    iosBundleId: 'com.example.authTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_6hhRq3C_V8VCfCu2V8DosRT29aar5F8',
    appId: '1:1039245326162:web:68e9faae348fb2be9aac8b',
    messagingSenderId: '1039245326162',
    projectId: 'flutter-auth-7e3ae',
    authDomain: 'flutter-auth-7e3ae.firebaseapp.com',
    storageBucket: 'flutter-auth-7e3ae.firebasestorage.app',
  );
}
