// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7LghGI47rBjfI0Oz7E6cdnsbkaOiRiN0',
    appId: '1:758660118532:web:3d9dbee5f2bbdf239f5d51',
    messagingSenderId: '758660118532',
    projectId: 'crud-app-3a466',
    authDomain: 'crud-app-3a466.firebaseapp.com',
    storageBucket: 'crud-app-3a466.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QyauXahsAfOFDTpO2sgKRTkOpNWKcn8',
    appId: '1:758660118532:android:64ec0bda7cd13acf9f5d51',
    messagingSenderId: '758660118532',
    projectId: 'crud-app-3a466',
    storageBucket: 'crud-app-3a466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxeVUSamV-DO2BaJLxgG5myuKAp-FPtiM',
    appId: '1:758660118532:ios:586a50f15b1bfcfe9f5d51',
    messagingSenderId: '758660118532',
    projectId: 'crud-app-3a466',
    storageBucket: 'crud-app-3a466.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxeVUSamV-DO2BaJLxgG5myuKAp-FPtiM',
    appId: '1:758660118532:ios:586a50f15b1bfcfe9f5d51',
    messagingSenderId: '758660118532',
    projectId: 'crud-app-3a466',
    storageBucket: 'crud-app-3a466.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7LghGI47rBjfI0Oz7E6cdnsbkaOiRiN0',
    appId: '1:758660118532:web:36a4d9713059e0649f5d51',
    messagingSenderId: '758660118532',
    projectId: 'crud-app-3a466',
    authDomain: 'crud-app-3a466.firebaseapp.com',
    storageBucket: 'crud-app-3a466.firebasestorage.app',
  );
}
