// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDescymTCV9R-zuvFjbklrGGF1kOfZB8q8',
    appId: '1:697824291701:web:58f4a0fb1d84d2b365c13c',
    messagingSenderId: '697824291701',
    projectId: 'real-time-database-3a53e',
    authDomain: 'real-time-database-3a53e.firebaseapp.com',
    databaseURL: 'https://real-time-database-3a53e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-3a53e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEg5DNUJlzhkCPanLQvTdioyGNbYZBq6E',
    appId: '1:697824291701:android:89811462615f21d165c13c',
    messagingSenderId: '697824291701',
    projectId: 'real-time-database-3a53e',
    databaseURL: 'https://real-time-database-3a53e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-3a53e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeacgH_e6R_CV_jcLwAvgUT_-854Dtmmw',
    appId: '1:697824291701:ios:a6cd194b4fd3d6ef65c13c',
    messagingSenderId: '697824291701',
    projectId: 'real-time-database-3a53e',
    databaseURL: 'https://real-time-database-3a53e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-3a53e.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeacgH_e6R_CV_jcLwAvgUT_-854Dtmmw',
    appId: '1:697824291701:ios:a6cd194b4fd3d6ef65c13c',
    messagingSenderId: '697824291701',
    projectId: 'real-time-database-3a53e',
    databaseURL: 'https://real-time-database-3a53e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-3a53e.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDescymTCV9R-zuvFjbklrGGF1kOfZB8q8',
    appId: '1:697824291701:web:09431796e63550b765c13c',
    messagingSenderId: '697824291701',
    projectId: 'real-time-database-3a53e',
    authDomain: 'real-time-database-3a53e.firebaseapp.com',
    databaseURL: 'https://real-time-database-3a53e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'real-time-database-3a53e.appspot.com',
  );
}
