// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREa25073T2Fkh1qpMdrVYJhkM91Y2GkU',
    appId: '1:849692686471:web:5d0945e37ae18f854f2022',
    messagingSenderId: '849692686471',
    projectId: 'auth-f0c67',
    authDomain: 'auth-f0c67.firebaseapp.com',
    storageBucket: 'auth-f0c67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHLFMJOlq379n8_5gDfSGmJIrKHd-z2Eo',
    appId: '1:849692686471:android:c8a7883ae507ae1c4f2022',
    messagingSenderId: '849692686471',
    projectId: 'auth-f0c67',
    storageBucket: 'auth-f0c67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOta0XBEaI6jq8-DVzZaqpdOvZO3yml_4',
    appId: '1:849692686471:ios:62c9e3915a9d1a434f2022',
    messagingSenderId: '849692686471',
    projectId: 'auth-f0c67',
    storageBucket: 'auth-f0c67.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOta0XBEaI6jq8-DVzZaqpdOvZO3yml_4',
    appId: '1:849692686471:ios:62c9e3915a9d1a434f2022',
    messagingSenderId: '849692686471',
    projectId: 'auth-f0c67',
    storageBucket: 'auth-f0c67.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBREa25073T2Fkh1qpMdrVYJhkM91Y2GkU',
    appId: '1:849692686471:web:434841458f57ae0a4f2022',
    messagingSenderId: '849692686471',
    projectId: 'auth-f0c67',
    authDomain: 'auth-f0c67.firebaseapp.com',
    storageBucket: 'auth-f0c67.firebasestorage.app',
  );
}
